import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AddUpdateProductComponent } from '../components/add-update-product/add-update-product.component';
import { 
  IonAccordion, 
  IonAccordionGroup, 
  IonButton, 
  IonButtons, 
  IonContent, 
  IonFooter, 
  IonHeader, 
  IonIcon, 
  IonImg, 
  IonItem, 
  IonLabel, 
  IonList, 
  IonMenu, 
  IonMenuButton, 
  IonMenuToggle, 
  IonRadio,
  IonInput, 
  IonRadioGroup, 
  IonRouterOutlet, 
  IonTitle, 
  IonToolbar, 
  IonCheckbox,
  IonCard,
  IonCardHeader,
  IonCardContent,
  IonCardTitle,
  IonCardSubtitle,
  IonFab,
  IonFabButton
} from '@ionic/angular/standalone';


@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    IonContent, 
    IonHeader, 
    IonFooter,
    AddUpdateProductComponent,
    IonTitle, 
    IonToolbar,
    IonAccordion,
    IonLabel,
    IonItem,
    IonAccordionGroup,
    IonMenu,
    IonMenuToggle,
    IonButton,
    IonImg,
    IonToolbar,
    IonMenuToggle,
    IonButtons,
    IonMenuButton,
    IonIcon,
    IonList,
    IonRadioGroup,
    IonRadio,
    IonInput,
    IonCardTitle,
    IonCardSubtitle, 
    IonCardHeader, 
    IonCard, 
    IonCardContent,
    IonCheckbox,
    IonRouterOutlet,
    FormsModule,
    IonFab,
    IonFabButton
  ],
  exports:[
    CommonModule,
    IonContent, 
    IonHeader,
    IonFooter,
    AddUpdateProductComponent, 
    IonTitle, 
    IonToolbar,
    IonAccordion,
    IonLabel,
    IonItem,
    IonAccordionGroup,
    IonMenu,
    IonMenuToggle,
    IonButton,
    IonImg,
    IonToolbar,
    IonMenuToggle,
    IonButtons,
    IonMenuButton,
    IonIcon,
    IonList,
    IonRadioGroup,
    IonRadio,
    IonInput,
    IonCardTitle,
    IonCardSubtitle, 
    IonCardHeader, 
    IonCard, 
    IonCardContent,
    IonCheckbox,
    IonRouterOutlet,
    FormsModule,
    IonFab,
    IonFabButton
  ]
})
export class SharedModule { }
